version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - "8080:8080"
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root